### ISSUE TITLE
Top and Bottom Text - Selection and Delete issue in browsers except Firefox

### ISSUE THREAD

**Issue by hirenvjoshi** [MakG10/jquery-meme-generator#3] opened 2016-11-08 13:06 UTC
I checked the demo but I am not able to select the text using Ctrl + A and even if I select it using mouse , I am not able to delete it using Del key. Even back arrow key is also not working. I can only delete the text using backspace.

This issue is not coming in Firefox but I checked in Chrome and Safari latest version and found this issue.

If possible, please let me know what is the issue.

Thanks

**Comment by MakG10** [comment] 2016-11-09 09:59
Hi. I can reproduce similar behaviour on Chrome, the Firefox seems to handling it fine in my case. I will investigate this issue later today, thanks for letting me know.

**Comment by hirenvjoshi** [comment] 2016-11-10 09:39
Thanks for checking issue and replying promptly.

Thanks,
Hiren Joshi

On Wed, Nov 9, 2016 at 3:29 PM +0530, "MakG10" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi. I can reproduce similar behaviour on Chrome, the Firefox seems to handling it fine in my case. I will investigate this issue later today, thanks for letting me know.

##

**Comment by MakG10** [comment] 2016-11-10 12:04
The problem was due to `forceUppercase` option transforming text directly on value of input field. It's fixed now.

**Comment by hirenvjoshi** [comment] 2016-11-10 14:45
Hmm. Seems like resolved. Good job.

Thanks,
Hiren Joshi

On Thu, Nov 10, 2016 at 5:34 PM +0530, "MakG10" <notifications@github.com<mailto:notifications@github.com>> wrote:

The problem was due to forceUppercase option transforming text directly on value of input field. It's fixed now.

##

**Closed as completed** 2016-11-10 17:37 UTC
